// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD7MP3QxtQBZOOUGA1BFkYSm9ir9Xz6phQ',
    appId: '1:55746414417:web:cce4ad9846c0ec81643570',
    messagingSenderId: '55746414417',
    projectId: 'otherwise-3fbbe',
    authDomain: 'otherwise-3fbbe.firebaseapp.com',
    storageBucket: 'otherwise-3fbbe.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBYZeAYywU5WYTZ0tHscmZPQJ9a6c9Otns',
    appId: '1:55746414417:android:0d938ce7dedad344643570',
    messagingSenderId: '55746414417',
    projectId: 'otherwise-3fbbe',
    storageBucket: 'otherwise-3fbbe.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAKJ5yXjEtEEyV9eWVEe96BuicnBpGhu74',
    appId: '1:55746414417:ios:a4aa723a05fb6e01643570',
    messagingSenderId: '55746414417',
    projectId: 'otherwise-3fbbe',
    storageBucket: 'otherwise-3fbbe.appspot.com',
    iosBundleId: 'com.example.otherwise',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAKJ5yXjEtEEyV9eWVEe96BuicnBpGhu74',
    appId: '1:55746414417:ios:e9aa55035676dbcd643570',
    messagingSenderId: '55746414417',
    projectId: 'otherwise-3fbbe',
    storageBucket: 'otherwise-3fbbe.appspot.com',
    iosBundleId: 'com.example.otherwise.RunnerTests',
  );
}
